### ISSUE TITLE
Bewegungsmelder Kamera

### ISSUE THREAD

**Issue by derpate1989** [holomekc/ioBroker.bshb#100]
Hallo, 
Ist es möglich den Bewegungsmelder der Kamera im iobroker darzustellen? Ich möchte diesen nutzen um bei Bewegung Hue Leuchten in der Einfahrt einzuschalten.

**Comment by holomekc** [comment]
I am afraid this is not possible:

the cameras are controlled by a different system which is more working via Internet. Also a dedicated app is used for that. The cameras are only linked to the Bosch Smart Home Controller and when you check the following api you can see that only privacy mode can be set:

https://apidocs.bosch-smarthome.com/local/#/

**Comment by derpate1989** [comment]
Ok thanks for the Information. :)
