### ISSUE TITLE
Werte in open doors und Windows sind nicht korrekt?

### ISSUE THREAD

**Issue by sven-s-ter** [holomekc/ioBroker.bshb#135]
**Describe the bug**  
Die Werte in open Doors an Windows unter z.B.

bshb.0.openDoorsAndWindows.all.all

werden bei mir wie folgt dargestellt:

{"type":"state","common":{"name":"All","type":"array","role":"list","read":true,"write":false},"native":{"id":"openDoorsAndWindows.all.all","name":"all.all"},"from":"system.adapter.bshb.0","user":"system.user.admin","ts":1632156272291,"_id":"bshb.0.openDoorsAndWindows.all.all","acl":{"object":1636,"state":1636,"file":1632,"owner":"system.user.admin","ownerGroup":"system.group.administrator"},"_bshbCreated":false}

**Expected behavior**  
Sollte Array mit Namen sein 

**Screenshots & Logfiles**  
<img width="2560" alt="Bildschirmfoto 2022-04-02 um 13 18 13" src="https://user-images.githubusercontent.com/71233096/161380845-2d26ef3f-24ca-4b62-87f5-39a2106bbd2b.png">

**Versions:**
- Adapter version: 0.1.19
- JS-Controller version: 4.0.21
- Node version: v14.19.1
- Operating system: debian auf Raspberry Pi4 8GB

**Additional context**  
Verson 0.1.18 läuft einwandfrei.

Grüße
Sven

**Comment by holomekc** [comment]
Hi. Vielen Dank für das Feedback. Das habe ich leider total übersehen :( 
Ist jetzt in 0.1.20 wieder behoben. Version ist auf GitHub und npm verfügbar. Ansonsten 1 Tag ca warten für Release in ioBroker.

Schönes Wochenende
Christopher
