### ISSUE TITLE
HumidityLevelService is missing in wall thermostat

### ISSUE THREAD

**Issue by dominikspeh** [holomekc/ioBroker.bshb#146]
**Describe the bug**  
Could you provide the HumidityLevelService in the wall thermostat? Currently inside of an iobroker thermostat object only temperature level appears. 

Thanks for this great plugin! :)

**Expected behavior**  
Humidity values appear in iobroker

**Versions:**
- Adapter version: 0.1.20
- JS-Controller version: 4.0.23
- Node version: 14.19.1
- Operating system:  Raspberry Pi OS

**Comment by jpawlowski** [comment]
It is here for my underfloor heating actors. Maybe it helps to name the specific devices where you're missing humidity values?

**Comment by holomekc** [comment]
Hi I will take a look asap if I find the time. Normally the Adapter shows everything without actually knowing much about the different devices. The API of Bosch is normally structured in a way which makes this possible. The benefit is that the adapter does not care about the different devices but just shows the values. So "all" naming is from API.  If something is missing it is mostly an indication for a new api interface. I normally have a concept how to include additional api endpoints e.g. Open windows, scenarios, etc.

**Comment by jpawlowski** [comment]
The HmIP documentation I mentioned in https://github.com/holomekc/ioBroker.bshb/issues/155#issuecomment-1152292375 might be useful here as well, assuming Bosch is not reinventing the wheel each time and might simply not expose each and every detail with their own API.
