### ISSUE TITLE
Convert level states to percentage unit

### ISSUE THREAD

**Issue by jpawlowski** [holomekc/ioBroker.bshb#155]
I am using BSHB in combination with [ioBroker.shuttercontrol](https://github.com/simatec/ioBroker.shuttercontrol). The adapter is designed to manage percentage values for shutter levels.

It looks like [ioBroker.hm-rpc](https://github.com/ioBroker/ioBroker.hm-rpc) is converting the internal float values to integer percentage values by implementing a [`level.blind` role](https://github.com/ioBroker/ioBroker.hm-rpc/blob/5cf6f746d2249aaf3671d04f19c2e3099e3b6700/src/lib/roles.ts#L11) (and others like `level.dimmer`).

I would love to see the same handling being implemented in the BSHB adapter as well to have feature parity with HomeMatic.

**Comment by holomekc** [comment]
At the moment the adapter shows the keys and values as they are provided by the api. 

There are a few mappings where based on the key different assumptions are  taken into account. E.g for roles. So in case we want to map values I would need to extend the "mapping" and tell the adapter when it finds a specific key it should map the value before showing it.

So it is possible first of all. The only thing is that I do not know all available keys. They are also not documented. So it was always a try and error approach for me most of the time. This is why I decided to show keys and values as the api provides. So the adapter is sort of stupid and as said just shows keys and values. I also do not own all Bosch devices which makes that quite hard for me.

But maybe this excuse is not that great. If you provide a list/screenshot of all the values of a bosch shutter I could check if there is a sort of elegant way to include the feature your requested. 

But this would introduce a breaking change to older versions. This is something which I typically try to avoid. I do not know which logic people are creating and then would fail afterwards. Also not sure if this is something the value providing adapter should solve or the logic/displaying providing adapter should handle. But I understand that the role suggest a different value type.

Regarding feature parity. This is really hard for me to understand. Which features are missing? I am also not sure if I want / can achieve that.

**Comment by jpawlowski** [comment]
I can give you some clarity and certainty here.
As Bosch uses quite many HomeMatic devices and their firmware is quite similar to eQ-3 devices, the Bosch API takes over lots of namings and values from the original eQ-3 API. You can get lots of information and hints about it from the [Homematic IP Devices - Technical Documentation](https://homematic-ip.com/sites/default/files/downloads/HmIP_Device_Documentation-1.40.10.pdf).

You are looking for page 746 to find information about the shutter actuator (in this case). The parameters here should somehow remind to the Bosch API values I suppose.

For the `LEVEL` attribute, mapping is actually fairly straight forward as it is a simple math like this:
![image](https://user-images.githubusercontent.com/75446/173058564-da243b7b-7477-40fc-b37e-642259db0081.png)

Don't worry, I am not requesting to implement ALL the details 😅 just some major important ones like assigning the correct unit mapping to `LEVEL` (also `PCT` but that might be a legacy value I just recall from classical HomeMatic which is out of scope for Bosch, of course).

About breaking changes... Appreciate your caution but think this is not as huge as a problem you might have in other home automation systems (I'd rather not mention... 🤐). As ioBroker uses a [semantic versioning](https://semver.org/) system, you might simply increase the correct number in combination with prober end-user communication as part of the change log.
I have seen breaking changes for ioBroker many times and I personally do prefer moving forward and not keeping old stuff "just because" (that unfortunately is the philosophy of the other 20 years old HA system I'm not naming… and people don't like it and have moved on to modern systems like ioBroker now).

(Dev)Life is change, embrace the change and act accordingly 🙃

[Appologies for my monologue, couldn't resist due to my professional background in change management]

**Comment by holomekc** [comment]
Hi. Sorry for the late answer. I could find some time to check this. I am sorry but I compared a Thermostat from Bosch with the Documentation you mentioned. But the key and values do not match. Bosch uses the following structure:

Device -> DeviceService

Here an example:
```json
  "native": {
    "device": {
      "@type": "device",
      "rootDeviceId": "xxx",
      "id": "hdm:HomeMaticIP:xxx",
      "deviceServiceIds": [
        "Thermostat",
        "BatteryLevel",
        "ValveTappet",
        "TemperatureLevel",
        "Linking",
        "TemperatureOffset"
      ],
      "manufacturer": "BOSCH",
      "roomId": "hz_1",
      "deviceModel": "TRV",
      "serial": "yyy",
      "profile": "GENERIC",
      "name": "Thermostat",
      "status": "AVAILABLE",
      "parentDeviceId": "roomClimateControl_hz_1",
      "childDeviceIds": []
    },
    "deviceService": {
      "@type": "DeviceServiceData",
      "id": "ValveTappet",
      "deviceId": "hdm:HomeMaticIP:xxx",
      "state": {
        "@type": "valveTappetState",
        "value": "VALVE_ADAPTION_SUCCESSFUL",
        "position": 0
      },
      "path": "/devices/hdm:HomeMaticIP:xxx/services/ValveTappet"
    },
```

Iam using the ids and the state information. So here:
key:
hdm:HomeMaticIP:xxx -> ValveTappet -> valveTappetState

value:
VALVE_ADAPTION_SUCCESSFUL

position:
0

I cannot find these values in the documentation. So in your case I guess there could be a key called hdm:HomeMaticIP:xxx -> ShutterControl -> shutterControlState

But I am not sure. I do not have such a device.  

Or am I missing something? :(
