### ISSUE TITLE
TwinGuard lässt sich nicht konfigurieren ("Gesunde Raumluft") 

### ISSUE THREAD

**Issue by NutzerXY** [holomekc/ioBroker.bshb#156]
**Describe the bug**  
Ich habe es leider nicht geschafft, meinen TwinGuard mittels des ioBroker.bshb zu steuern. Ich sehe zwar in dem Objekt "bshb.0.updates" updates der Form 

```json
{
    "configuration": {
        "actuators": {
            "red": {
                "mode": "BLINKING",
                "lights": []
            },
            "green": {
                "lights": []
            },
            "yellow": {
                "lights": []
            },
            "pushNotificationEnabled": true
        },
        "operatingHours": {
            "startTime": "16:00",
            "endTime": "21:00",
            "alwaysOn": false
        },
        "sensitivity": "HIGH"
    },
    "@type": "airPurityGuardian",
    "staticSensitivityLevels": {
        "high": [
            1000,
            1500
        ],
        "low": [
            2000,
            2500
        ],
        "medium": [
            1500,
            2000
        ]
    },
    "lightActuators": [
        "hdm:PhilipsHueBridge:HueLight_0017880109307d4e-0b_ecb5fa182149",
        "hdm:PhilipsHueBridge:HueLight_0017880109309aab-0b_ecb5fa182149",
        "hdm:PhilipsHueBridge:HueLight_00178801092b4215-0b_ecb5fa182149",
        "hdm:PhilipsHueBridge:HueLight_0017880109631af7-0b_ecb5fa182149",
        "hdm:PhilipsHueBridge:HueLight_00178801061cff2a-0b_ecb5fa182149",
        "hdm:PhilipsHueBridge:HueLight_0017880104056029-0b_ecb5fa182149",
        "hdm:PhilipsHueBridge:HueLight_00178801096321af-0b_ecb5fa182149",
        "hdm:PhilipsHueBridge:HueLight_00178801092d9b60-0b_ecb5fa182149",
        "hdm:PhilipsHueBridge:HueLight_001788010971f1a6-0b_ecb5fa182149",
        "hdm:PhilipsHueBridge:HueLight_0017880109309793-0b_ecb5fa182149",
        "hdm:PhilipsHueBridge:HueLight_00178801092a9d7a-0b_ecb5fa182149",
        "hdm:PhilipsHueBridge:HueLight_00178801092b4204-0b_ecb5fa182149"
    ],
    "name": "Schlafzimmer",
    "id": "airPurityGuardian_hz_4",
    "enabled": true
}
```
jedoch kann ich kein Objekt mit dem Namen `airPurityGuardian_hz_4` finden, über welches ich die Funktion "Gesunde Raumluft" des TwinGuards ein- oder ausschalten könnte.

**To Reproduce**  

0. Kaufe einen TwinGuard 😉 
1. Konfiguriere den TwinGuard über Bosch
2. Stelle in IOBroker fest, dass es in IOBroker nur einen "Rauchmelder" gibt, ohne jegliche Möglichkeiten der Konfiguration der Funktion "Gesunde Raumluft".

**Expected behavior**  
Ich hätte erwartet, dass ich mittels diesem Adapter meinen TwinGuard konfigurieren könnte.

**Screenshots & Logfiles**  

<img width="936" alt="Bildschirmfoto 2022-06-29 um 19 31 22" src="https://user-images.githubusercontent.com/94020939/176499647-6c0a9b08-3be3-4cc7-8fdc-aebe856d3314.png">

**Versions:**
- Adapter version: 0.1.20
- JS-Controller version: 4.0.23
- Node version: v12.22.7
- Operating system: Docker Container (buanet/iobroker)

**Additional context**  
TwinGuard sendet mit der Funktion "Gesunde Raumluft" Benachrichtigungen wenn die Luft "verbraucht" ist. Jedoch ist es nicht hilfreich, wenn ich diese Notifications bekomme wenn keiner zuhause ist (und die Fenster öffnen kann). Daher versuche ich über diesen Adapter die Funktion dynamisch an bzw. aus zuschalten.

**Comment by holomekc** [comment]
Hi,
sorry für die späte Meldung. Ich schaue mir das mal am Wochenende an. Es müsste gehen. Ich muss jedoch noch herausfinden wie :D. Ich sehe jedoch:


```json
{"configuration":{"actuators":{"red":{"mode":"BLINKING","lights":[]},"green":{"lights":[]},"yellow":{"lights":[]},"pushNotificationEnabled":true},"operatingHours":{"startTime":"08:00","endTime":"22:00","alwaysOn":true},"sensitivity":"MEDIUM"},"@type":"airPurityGuardian","staticSensitivityLevels":{"high":[1000,1500],"low":[2000,2500],"medium":[1500,2000]},"lightActuators":[],"name":"Wohnzimmer","id":"airPurityGuardian_hz_2","enabled":true}

{"configuration":{"actuators":{"red":{"mode":"BLINKING","lights":[]},"green":{"lights":[]},"yellow":{"lights":[]},"pushNotificationEnabled":true},"operatingHours":{"startTime":"08:00","endTime":"22:00","alwaysOn":true},"sensitivity":"MEDIUM"},"@type":"airPurityGuardian","staticSensitivityLevels":{"high":[1000,1500],"low":[2000,2500],"medium":[1500,2000]},"lightActuators":[],"name":"Wohnzimmer","id":"airPurityGuardian_hz_2","enabled":false}
```

Der Wert airPurityGuarding_hz_2 ist es wohl. Ich schaue mal, ob ich das setzen kann. Ich denke jedoch das dies Teil eines anderen API Endpunktes ist. Mal schauen.

**Comment by holomekc** [comment]
Version 0.2.0 ist in GitHub und NPM verfügbar und kann getestet werden. ioBroker release dauert vielleicht ein bissle.
Fall Probleme auftreten einfach wieder melden.

Viele Grüße und viel Spaß
Christopher
