### ISSUE TITLE
[Question] - Device Status

### ISSUE THREAD

**Issue by daloki83** [holomekc/ioBroker.bshb#186]
Hello,

would it be possible to get a device status like "Online/Offline" or "last seen at..."?
After Restart/Update etc. it took sometimes hours until all devices are connected. With that Status (like in the App) we could trigger other thing to be informed.

**Comment by holomekc** [comment]
Hi @daloki83 
Sorry for the late response. I will take a look on my weekend.

Br,
Chris

**Comment by holomekc** [comment]
Hi @daloki83,
status is available when you install the adapter here from GitHub:
![image](https://user-images.githubusercontent.com/30546982/215228124-af139ab6-908d-465c-b0ce-d33be592e763.png)

Values:
`
AVAILABLE
DISCOVERED
UNAVAILABLE
COMMUNICATION_ERROR
UNDEFINED
`

As you mentioned it may take some time until this is recognized. It it quite fast in case you try to use a device though.

**Comment by holomekc** [comment]
No further questions or feedback. So I close this one.
