### ISSUE TITLE
Room Thermostat II - Humidity Level missing

### ISSUE THREAD

**Issue by kesch001de** [holomekc/ioBroker.bshb#204]
Hi Chris, 
Using the new Room Thermostat v2, it does not show the humidity level anymore in the object list.
Is that not supported/provided by the API anymore or can that be adjusted?
Thanks, 
Kevin

**Expected behavior**  
Objects List Verson 1 Room Thermostat includes the humidity level.

**Screenshots & Logfiles**  
Object List Version 2 Room Thermostat:
![image](https://user-images.githubusercontent.com/68777942/211188087-dd10b18a-93cf-4023-8428-fc43f7774140.png)

**Versions:**
- Adapter version: 0.2.1
- JS-Controller version: 4.0.24
- Node version:  v16.19.0
- Operating system: RaspberryPI/Linux

**Comment by holomekc** [comment]
Hi @kesch001de 
The values from the picture are all provided by one endpoint. So normally no value should be missing. So i think three options. 
1. V2 does not have a humidity sensor anymore
2. Bosch created a new api endpoint just for that. I cannot really imagine why this should be necessary
3. A bug in my adapter

I wanted to test the V2 anyway so if you give me some time I can try to figure this out. 

I quickly checked the Bosch app. The humidity value is not visible there right? Or am I blind? So I think 1. is acutally the reason. That would be sad😢.

I will try to check after my vacation.

**Comment by kesch001de** [comment]
hi @holomekc, 
Thanks for your very quick reply. 
It does support the humidity and the app shoes it as usual in the rooms dashboard.
Maybe option 3 is not that wrong, since it has more features and you can even add additional sensors.

Many thanks for looking into it - much appreciated 👍

**Comment by holomekc** [comment]
Hi @kesch001de,
I am an idiot. Sorry I read your text but ignored the room infront of Thermostat... you are right. I will check that.i tried to quickly check the bosch api. I cannot access it at the moment:

https://apidocs.bosch-smarthome.com/local/

Maybe it works later.

**Comment by holomekc** [comment]
Hi @kesch001de,

Ok the room thermostat arrived. I breathed on it very strongly :) and yes there is something:
`{"iconId":"icon_room_living_room","extProperties":{"humidity":"81.5"},"@type":"room","name":"Wohnzimmer","id":"hz_2"}`

This looks like a room data entry. So I checked that and yes I can see this response. More or less the same as already posted above:
` {"@type":"room","id":"hz_2","iconId":"icon_room_living_room","name":"Wohnzimmer","extProperties":{"humidity":"56.76"}}`

Long story short. 0.2.1 is pushed in GitHub. So you can test it by installing from GitHub. I added rooms. I am not sure yet if I can manage to write values to controller. E.g. changing name and iconId. I need to check the API documentation for that, but the local api is not available at the moment:  BoschSmartHome/bosch-shc-api-docs#70

I am not sure which values exist in room. I only have humidity at the moment. So "fancy" features like role and unit is only supported for humidity value.

Sorry that it took that long. Feedback would be awesome.

**Comment by kesch001de** [comment]
hi @holomekc,
Many thanks for your feedback and looking into it - much appreciated!

I guess i broke it ...
![image](https://user-images.githubusercontent.com/68777942/212540362-2b7dfd94-10a0-4119-b216-544ad4fdd1e0.png)

The adaptor does not start anymore now.

**Comment by holomekc** [comment]
Hi @kesch001de 
No you did not. I forgot to push something... Try again.

**Comment by kesch001de** [comment]
hi @holomekc, 
That looks better 👍 
I can see a new section 'rooms' now. It shows the humidity. Great!

Question: 
Will that change for the temperature as well? Or is it for the humidity only (as of the moment)?

Thanks for your support!

**Comment by holomekc** [comment]
Hi @holomekc 
At the moment I follow the structure of Bosch here. The benefit is that all additional values I do not know about besides humidity would work out of the box. I think I could move the values to roomClimate of the suitable room but I am not sure about this. As said I do not know what other values exist and maybe they do not fit into the climate category. 

Is it an issue that the humidity value is in the room folder?

I am not sure if Bosch moves more values to room. It seems like that the ...2 devices are not Homematic anymore but instead plain Zigbee. Most likely also the reason why the Controller2 does not support the old devices. Ok I drifted away. Ehm. No I have no plans moving other values around. Except Bosch changes it. 

Technical explanation. I have so called Handler for more or less every API Endpoint. That helps to separate things. Although it is possible to mix the results/values in whatever iobroker structure I want it also makes it messy. So I like to keep it simple. Also I do not have that much time for the open source projects.

**Comment by kesch001de** [comment]
hi @holomekc 
Well, i guess thats all fine and I guess its absolutely the right place to add it to the room.

Just one concern actually.
Since its taking the humidity from the room now, there is no link to a device anymore.
So in case a Twinguard and a Room Thermostat are within the same room, you dont know which one is shown/used.
But anyways, the Twinguard still shows the humidity for itself - so actually all good.

**Comment by holomekc** [comment]
Hi @kesch001de 
The humidity of the twinguard is still at the device. This did not change. When you check the json example I posted above you can see that there is no indication where this humidity value comes from. So I am actually not able to tell which device sent this value.

**Comment by holomekc** [comment]
I guess it is done. In case there is something missing please let me know.
