### ISSUE TITLE
Einstellen der Raumtemperatur-Programme nach neuem Bosch-Update

### ISSUE THREAD

**Issue by NutzerXY** [holomekc/ioBroker.bshb#223]
Hallo in die Runde,

nach dem neuesten Update des Bosch-Smart-Home-Controllers, ist es möglich, mehrere individuelle Raumtemperatur-Programme für alle Heizkörperthermostate zu erstellen.

Diese möchte ich nun gerne mittels IoBroker ändern können.

Im Objekt:
bshb.0.roomClimateControl_hz_1.RoomClimateControl sehe ich die Auswahlmöglichkeiten (States):

- "MANUAL"
- "AUTOMATIC"
- "OFF",
-  "UNKNOWN" 

Außerdem wird mir bei: bshb.0.roomClimateControl_hz_1.RoomClimateControl.schedule bei der Auswahl eines bestimmten Zeitprogramms in der Bosch-App das Zeitprogramm angezeigt. 
z.B.:
{"profiles":[{"switchPoints":[{"startTimeMinutes":0,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":510,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":1050,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":1275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}}],"day":"MONDAY"},{"switchPoints":[{"startTimeMinutes":0,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":510,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":1050,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":1275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}}],"day":"TUESDAY"},{"switchPoints":[{"startTimeMinutes":0,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":510,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":1050,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":1275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}}],"day":"WEDNESDAY"},{"switchPoints":[{"startTimeMinutes":0,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":510,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":1050,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":1275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}}],"day":"THURSDAY"},{"switchPoints":[{"startTimeMinutes":0,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":510,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":1050,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":1275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}}],"day":"FRIDAY"},{"switchPoints":[{"startTimeMinutes":0,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":510,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":1045,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":1275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}}],"day":"SATURDAY"},{"switchPoints":[{"startTimeMinutes":0,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":510,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}},{"startTimeMinutes":1050,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"COMFORT"}},{"startTimeMinutes":1275,"value":{"@type":"temperatureLevelSwitchPointValue","temperatureLevel":"ECO"}}],"day":"SUNDAY"}]}

Leider kann ich diesen seitens IoBroker nicht verändern.

Wäre es möglich, eine Funktion zu implementieren, um die Zeitprogramme über IoBroker ändern zu können?

Vielen Dank und liebe Grüße!!

**Comment by holomekc** [comment]
Hi. Auf der ersten Blick scheint mir das ein App spezifisches Feature zu sein. Wenn ich in der App zwischen den Zeitplänen wechsle, dann sehe ich nur Änderungen an dem Objekt schedule (über updates Objekt sichtbar, dort werden alle Änderungen dem Adapter mitgeteilt). Heißt für mich Bosch ändert das über die App selber und es scheint kein extra Wert zu sein. Über Szenarien scheint man das auch nicht umstellen zu können. Ich kann nach meinem Urlaub noch einmal genauer schauen.

was ich bisher gemacht habe ist, dass ich über schedule selber 3 Profile (Anwesend, Abwesend, Urlaub) erstellt habe.

wenn es gehen sollte hätte ich es über RoomClimateControl erwartet, aber jetzt auf dem Smartphone sehe ich kaum was in ioBroker.

Froher Restostern noch

**Comment by NutzerXY** [comment]
Hi, 
das wäre schon echt ein cooles Feature, wenn man das irgendwie realisieren könnte! 

Zeitplan über Schedule kannte ich bisher noch nicht! Könntest du da kurz 3 Sätze mehr zu verlieren? 


… trotz dessen hoffe, dass es irgendwie über diese individuellen Programme Realisierbar wäre. So hätte man die in meinen Augen gelungene Visualisierung von Bosch sowie die Flexibilität von IoBroker…


Liebe Grüße!

**Comment by holomekc** [comment]
Hi,

ok es ist machbar. Ich brauche jedoch ein bissle Zeit dafür. Das ist eine andere Api und diese ist nicht dokumentiert. Ich sitze schon dran, aber keine Ahnung wie lange das dauert. Mal schauen.

Viele Grüße
Chris

**Comment by holomekc** [comment]
Hi,

die Version 0.2.3 ist jetzt in GitHub verfügbar. Falls es möglich ist würde ich mich über Feedback freuen.

Viele Grüße
Chris

**Comment by NutzerXY** [comment]
Hallo!
Habe mich soeben mal dran gesetzt und das neue Update überprüft: klappt alles so wie ich es mir vorgestellt habe! Die einzelnen Heizprogramme werden angezeigt und man kann diese ein und ausschalten.

Vielen Dank für den schnellen Support und die Umsetzung!

**Comment by holomekc** [comment]
Super! Freut mich das es klappt. Rein aus Interesse. Hast du die 0.2.3 getestet oder 0.2.4 habe ich kurz danach noch einmal erstellt. Mit ein paar Aufräumaktionen und bissle mehr. Node >= 16 ist aber voraussetzung

**Comment by holomekc** [comment]
Super. Danke!

in ClimateSchedule gibt es activeScheduleId. Dort kann auch die id gesetzt werden. Der Wert existiert zum lesen bereits an der Api und da dachte ich das man ihn dort auch setzten können sollte. Ich war nicht sicher was intuitiver ist.

**Comment by NutzerXY** [comment]
Ich habe leider doch einen Fehler festgestellt:
Beim Laden der Zeitpläne werden diese in der App korrekt angezeigt.
In einer Heizphase wurde zumindest bei mir heute Morgen jedoch nicht die Zieltemperatur an die jeweiligen Thermostate gesandt.
Um das hinzukriegen, musste ich in der App noch einmal händisch den Zeitplan auswählen…

**Comment by holomekc** [comment]
Hi,
Danke. Ich schaue noch einmal. Wäre eigentlich ein bisschen komisch. Der Endpunkt hat nur die id vom Zeitplan. Die Temperatur immer mit setzen kann nicht sein. Die App läuft ja auch nicht 24/7 und die Temperaturen stehen ja extra im Zeitplan. Bei mir hatten sich die Werte 2 min vor der eingestellten Zeit geändert. Ich teste noch einmal und melde mich dann.

**Comment by holomekc** [comment]
Hi,
Ne das geht bei mir. Was ich getestet habe ist:
Ich habe 3 Zeitpläne: home, away, vacation. Für den Test brauchen wir nur die ersten beiden.
Ich habe in der app den Zeitplan gewechselt: home -> away -> home. Also ist aktuell home aktiv.
Dann habe ich den Zeitplan away verändert und die Temperatur für einen Zeitraum auf 15 gestellt (10 min in der Zukunft. Wenn man schnell genug ist gehen auch 5). Alles in der App bestätigt aber immer noch Zeitplan home ist ausgewählt. App beendet. Gewartet und knapp 2 min vorher haben sich die Werte in iobroker verändert. Auch die Temperatur. Auch am Thermostat stehen 15 gerade.
Was komisch aussieht sind die eco und comfort Werte. Aber die Werte kommen so vom Controller.
 
was noch ein bissle schade ist, ist dass die „profile“ Werte sich nicht verändern, wenn ein Zeitplan bearbeitet wird. Das liegt daran, dass ich kein Update Event vom Controller erhalte. Glaube aber nicht das ich das ändern kann, da kann ich am WE noch einmal schauen.

**Comment by NutzerXY** [comment]
Ich habe mal 2 Screenshots gemacht! Vielleicht können sie das Problem ein bisschen besser umschreiben: 
![IMG_1474](https://user-images.githubusercontent.com/94020939/234252752-c62ebbba-6313-4432-a39d-20258600b2f9.png)
![IMG_1475](https://user-images.githubusercontent.com/94020939/234252759-f2ac7ba6-1b00-45f6-99b2-914750695582.jpeg)

**Comment by holomekc** [comment]
Hmm leider nicht wirklich:
Zeitplan, welchen ich über ioBroker verändert habe. Von home -> away
![IMG_4323](https://user-images.githubusercontent.com/30546982/234268660-bf0bd4b8-25e6-4382-a4b6-8b73636407b2.png)
Kurz bevor 15 eingestellt werden soll
![IMG_4325](https://user-images.githubusercontent.com/30546982/234268677-cf47657b-4484-453f-a368-72f31f86b173.png)
Nachdem 15 eingestellt werden soll
![IMG_4327](https://user-images.githubusercontent.com/30546982/234268688-77b72778-f4d4-4ecf-8d69-ebdca0584fad.png)

**Comment by NutzerXY** [comment]
Ich habe den Fehler gefunden! 
lag an meinen mangelnden informatischen Fähigkeiten! 
Jetzt funktioniert alles wie es soll!

**Comment by holomekc** [comment]
Super das es geht! Danke für das schnelle Feedback.
