### ISSUE TITLE
bshb Raumthermostat II ohne sinnvolle Datenpunkte

### ISSUE THREAD

**Issue by Ringo-66** [holomekc/ioBroker.bshb#255]
**Describe the bug**  
beim Raumthermostat II werden keinerlei Datenpunkte (außer Status: AVAILABLE) angezeigt.

**To Reproduce**  
1. bshb adapter (v0.2.4. ) ist grün, andere Geräte werden angezeigt und liefern mehrere Datenpunkte.
2. Gerät wurde über die BSH App hinzugefügt und kommuniziert, Parameter sind einstellbar
3. Adapterinstanz wurde restartet
4. Neuer Datenpunkt (siehe oben) wurde erzeugt, allerdings mit sehr spärlicher Information
5. See error

**Expected behavior**  
Alle am Gerät einstellbaren Parameter sicht und änderbart

**Screenshots & Logfiles**  
![grafik](https://github.com/holomekc/ioBroker.bshb/assets/135025038/2547a589-4b02-4cf6-b90d-bf5d004c4a71)

**Versions:**
- Adapter version: <v0.2.4.>
- JS-Controller version: <5.0.12> 
- Node version: <v18.17.0> 
- Operating system: <W11 pro>

**Additional context**

**Comment by holomekc** [comment]
Adapter stoppen, alle Objekte von bshb löschen, Adapter starten
