### ISSUE TITLE
Twinguard Alarm message

### ISSUE THREAD

**Issue by Draexl** [holomekc/ioBroker.bshb#257]
Can you see anywhere which Twinguard has reported an alarm?
Apparently this is not possible in the data points.
Even a “real” test alarm didn’t help me.

**Comment by Draexl** [comment]
More information:
I use two Twinguards (but could be more)
These are the data points I have.
Under the "smokeDetectionSystem
"Unfortunately I can't find any corresponding data point.
![Bildschirmfoto 2023-10-31 um 14 23 34](https://github.com/holomekc/ioBroker.bshb/assets/86128006/712f2395-4eb0-490d-ad28-88d1d65e9fc0)
![Bildschirmfoto 2023-10-31 um 14 23 51](https://github.com/holomekc/ioBroker.bshb/assets/86128006/05854358-42e1-485f-ab97-cc89f0510720)

**Comment by holomekc** [comment]
This was already discussed in the ioBroker forum:
https://forum.iobroker.net/topic/25370/test-adapter-bshb-bosch-smart-home-v0-0-x/379?_=1701506854811&lang=de

incidents is what you are looking for:
```json
[
  {
    "triggerName":"Schadstoffmelder Flur Oben",
    "locationId":"hz_2",
    "location":"Wohnungsflur",
    "id":"hdm:ZigBee:0000000000000",
    "time":1699128763267,
    "type":"SMOKE_PRIMARY"
  }
]
```
