### ISSUE TITLE
Hinzufügen von Zuständen in ioBroker

### ISSUE THREAD

**Issue by NutzerXY** [holomekc/ioBroker.bshb#258]
Guten Abend,

Nach dem neusten Update der Bosch App können nun neben Szenarien und Automation auch Zustände in der Bosch-App hinzugefügt werden. Nach meiner ersten Einschätzung handelt es sich hierbei um eine Art virtuelle Schalter, welche als Bedingungen in den Bosch-Automationen genutzt werden können.

Im Bereich des Update-Knotens in IoBroker kann nach Aktivieren eines solchen Zustandes, folgender Code entnommen werden:
{"deleted":false,"@type":"userDefinedState","name":"NameZustand","id":"26f35984-09be-479e-8990-8467f057ee75","state":true}

Könnte man diese Zustände analog zu den Szenarien in IoBroker integrieren?
Hierdurch hätte man (endlich) virtuelle Schalter, welche die Bosch-Automationen um ein vielfältiges mächtiger machen würden.

PS: Ich bin durch den Support hier mehr als begeistert! Hatte schon einige Issues erstellt und war danach immer voll und ganz happy!

Liebe Grüße!

**Comment by holomekc** [comment]
Hi @NutzerXY,

Ich bin dran. Danke für die lieben Worte
https://github.com/holomekc/bosch-smart-home-bridge/blob/master/CHANGELOG.md

Viele Grüße
Chris

**Comment by holomekc** [comment]
0.2.5 in GitHub und npm. Viel Spaß. Das war jetzt auf die schnelle. Falls etwas nicht passen sollte bitte bescheid geben.
Ich muss jetzt weg ;)

**Comment by NutzerXY** [comment]
Hi! 
Das ist ja mal wieder eine Wahnsinns Reaktionszeit! Habe ich gerade sofort getestet, nachdem ich nach Hause gekommen bin.
Was schonmal perfekt funktioniert: Zustände aus dem Bosch-Ökosystem auslesen. Auch Änderungen der Zustände werden in IoBroker dargestellt.
Was leider nicht funktioniert: Ändern der Zustände über IoBroker. Sie werden zwar auf der IoBroker-Oberfläche geändert angezeigt, jedoch werden sie nicht in der Bosch-App übernommen.

Liebe Grüße!

**Comment by holomekc** [comment]
Hmm. Eigentlich hatte ich das getestet. Kommen da Fehlermeldungen in deinem Protokoll. Ich baue immer von Hand… ich muss das mal nach GitHub verschieben. Vielleicht habe ich dabei was vermasselt.

**Comment by holomekc** [comment]
Ok es liegt an dem wie ich es gebaut habe. Ich baue gleich noch einmal eine neue Version. Ich prüfe noch einmal was da schief gelaufen ist...

**Comment by holomekc** [comment]
Ok so jetzt aber. 0.2.6 ist in GitHub verfügbar. Npm habe ich nicht gepushed, sonst erstelle ich da immer wieder neuere Versionen ;).

**Comment by NutzerXY** [comment]
Guten Morgen, entschuldige die verspätete Rückmeldung. Komme aber erst heute dazu, mich wieder mit dem Smarthome zu beschäftigen! Jetzt funktioniert alles wie es soll!

Vielen Dank!
