### ISSUE TITLE
Please add .npmignore to repo

### ISSUE THREAD

**Issue by GermanBluefox** [holomekc/ioBroker.bshb#27]
Red files have nothing to do in the npm packet:
![image](https://user-images.githubusercontent.com/4582016/80038477-06418580-84f6-11ea-909f-20600e18cf39.png)

**Comment by holomekc** [comment]
Thanks for the feedback. Is handled here:
https://github.com/holomekc/ioBroker.bshb/pull/28

**Comment by holomekc** [comment]
Travis green. Closing issue
