### ISSUE TITLE
Delay of aprox. 2 seconds when commanding a change, like light or blind

### ISSUE THREAD

**Issue by RkcCorian** [holomekc/ioBroker.bshb#278]
**Describe the bug**  
When I switch on / off a light or even when I command a blind, there is a delay of aprox. 2 seconds.
This is not there in the Bosch App and I check as well with a dummy in home assistant

**To Reproduce**  
1. Switch on / off a light or move the blind up / down

**Expected behavior**  
There is no recognizable delay between command and reaction

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**
- Adapter version: 0.2.6
- JS-Controller version: 5.0.16 
- Node version: iobroker -v 
- Operating system: docker

**Additional context**

**Comment by RkcCorian** [comment]
Many thanks upfront for your help!!!

**Comment by holomekc** [comment]
Hi @RkcCorian 
Thx for the feedback and the kind words. I am not sure how fit you are with programming. I need to drive for 7h now. So it would take some time for me to look into this issue. What you can try is: edit the main.js file in the iobroker.bshb directory. When you are in the main directory of iobroker: ./mode _modules/iobroker.bshb.

There you should find the main.js. If not there directly, maybe in build or something like this. 

Search for line ~91. there you should see that rateLimit is set/read from the config. After that just override it:
'''javascript
this.config.rateLimit = 0;
'''

The config in iobroker ui does not allow you to set it to 0 (min = 1000ms). I think my rate limit implementation is delaying all the time. Although it is set to 1s only, which does not fit to your description. But we will see.

I hope this helps you immediately. I will do some tests when I am back.

Br,
Chris

**Comment by RkcCorian** [comment]
@holomekc : Many many thanks!!! This does the job. Can you bring this change also officially? Wish you a good and safety travel!

**Comment by holomekc** [comment]
Hi @RkcCorian ,

First of all thanks again. I need to check. It is not really a fix. The issue which may occur now is when you send too many requests to the controller in a very short time period. The Controller might reject some requests. I guess the solution should be to really implement a rate limit. So max 1 request per configurable rateLimit time. E.g. 1 per second or 1 per 500ms or something like this. But it should not delay the initial requests when there was no request before ind the configured time window.

I guess i can also remove the minimum of 1000. so min would be 0, which disables the rate limit (but as said might create communication issues). I will take a look and do some tests soon-ish.

Br,
Chris

**Comment by RkcCorian** [comment]
Cool, looking forward

**Comment by holomekc** [comment]
Hi @holomekc,

you can try 0.2.7, which is available in GitHub and npm now. 

If you face issues, please let me know.

Br,
Chris

**Comment by RkcCorian** [comment]
Hi @holomekc!

Looks good for me. I configured now a delay of 10ms and works fine for me, also for group actions like commanding a couple of blinds or lights at the same time. Many many thanks for your fast support!!!

Greetings!
