### ISSUE TITLE
bshb Heizkörperthermostat II - Offset funktioniert nicht

### ISSUE THREAD

**Issue by simon2022** [holomekc/ioBroker.bshb#284]
**Describe the bug**  
Bei allen meinen "Heizkörperthermostat II" lässt sich leider kein Offset über den ioBroker einstellen.
Da ich jedoch externe Temperatur-Sensoren benutzen möchte, möchte ich gerne in Zukunft alle 15 Minuten die vom Heizkörperthermostat gemessene Temperatur mit der meines externen Temperatur-Sensors abgleichen und daraus einen Offset berechnen und automatisch setzen.

**To Reproduce**  

![chrome_xLcj1iwhwR](https://github.com/holomekc/ioBroker.bshb/assets/59486823/d0af17a1-d843-4bbe-b0d1-69a3ae8c1457)

Der Wert lässt sich zwar eintragen, wird aber nicht bestätigt (grün) und kommt auch nicht in der Bosch App an.
Auch der isSetPointTemperatureOffsetActive lässt sich zwar auf true setzen, bleibt aber im ioBroker ebenfalls nur rot und wird nicht grün.

**Expected behavior**  
Der unter setPointTemperatureOffset eingetragene Wert wird an das Bosch-System übertragen und lässt sich z.B. in den Einstellungen in der Bosch-App ablesen.

**Versions:**
- Adapter version: 0.2.6

**Additional context**  
Ich stehe gerne bei weiteren Fragen bereit und würde mich wirklich sehr freuen, wenn das Problem gelöst wird. Vielen Dank

**Comment by holomekc** [comment]
Hi,

bei meinem Thermostat 1 geht es ohne Probleme.
Bei meinem Thermostat 2 nimmt der Controller die Daten an, hat jedoch keine Auswirkungen. Ich habe aber aktuell auch ein Raumthermostat dran gekoppelt. Offset am Raumthermostat geht dann wieder. Die App aktualisiert bei mir nicht direkt, ich musste zurück und wieder ins Menü, erst dann war der neue Wert zu sehen.

Beim ersten Wert, also offset am Thermostat erhalte ich also Feedback vom Controller. Bei mir wird der Wert auch grün. Sowohl beim Raumthermostat als auch beim v1. 

ich weiß nicht, ob du auch ein Raumthermostat gekoppelt hast. Falls nicht bitte einmal den Adapter auf silly stellen und schauen was der Controller antwortet. Siehst du Fehler im log?

Bezüglich des anderen Wertes von climate control. Ich weiß nicht mal genau was dieser Wert machen soll. In der Api ist dieser nicht dokumentiert. Ich leite im Adapter immer alles weiter was über den Controller ausgegeben wird. Wenn ich versuche den Wert zu setzen sehe ich zwar, dass der Controller sich nicht beschwert, ich erhalte jedoch auch keine Bestätigung vom Controller das sich der Wert geändert hat. Das wäre untypisch zum bisherigen Verhalten vom Controller. Anders gesagt hier kann ich bestätigen was du meinst. Zumindest insofern, dass dieser Wert rot in iobroker bleibt. Ich weiß jedoch auch nicht was sich überhaupt verändern soll. Wo siehst du hier diese Option in der App?

Ich kann überlegen eine Liste an Werten zu sammeln, welche kein extra Feedback benötigen/liefern und dann direkt den Wert in ioBroker bestätigen. Ändert aber nicht viel an der Funktionalität des Adapters. Die Werte werden gesetzt. Das Feedback im Adapter ist nur nicht schön. Wenn ich jedoch vom Controller kein Feedback bekomme, müsste ich anfangen die Daten regelmäßig abzufragen (pollen), das würde ich aber gerne vermeiden. Das ist immer maximal ineffizient und ich müsste auch immer wieder alle Daten durchsuchen.

Kurz gesagt. Bitte nochmal testen mit logs. Ich schaue am Wochenende vielleicht mal und trenne das Raumthermostat und schauen, ob dann der Offset bei mir direkt am Thermostat geht oder nicht.
Bezüglich des anderen Werts wäre gut zu wissen welche Erwartung du an diesen hast. Ich sehe in der App keine Funktion, welche es erlaubt den Offset ein oder auszuschalten.

**Comment by simon2022** [comment]
Hallo,

vielen Dank für die schnelle Rückmeldung.
Ich werde heute Abend das ganze nochmal mit den Logs durchführen.

Ich brauche die zweite Funktion, von der du auch nicht weißt, was sie machen soll, gar nicht. Ich dachte einfach nur, dass man diese vielleicht setzen muss, dass es funktioniert.

Letztendlich will ich einfach einen externen Temperatursensor verwenden.
Und ich habe keinen offiziellen externen von Bosch, sondern zigbee von Aqara.

In der App von Bosch lässt sich bei mir allerdings der Offset ohne Probleme einstellen.

Ich melde mich nochmal mit den Logs.

Vielen Dank

**Comment by simon2022** [comment]
@holomekc 
Hier der Log vom ioBroker, wenn ich versuche, den Punkt **RoomClimateControl.setPointTemperatureOffset** auf 1.5 zu setzen
[offset.txt](https://github.com/holomekc/ioBroker.bshb/files/13927774/offset.txt)

Ich habe die Bosch App danach komplett neu gestartet, dennoch ist in den Einstellungen des Heizkörperthermostats immer noch ein Offset von 0.0 eingestellt

**Comment by holomekc** [comment]
Hi @simon2022,

das hilft direkt schon. Diese Werte bitte direkt am Gerät einstellen. Beim v2 bspw:
bshb.0.hdm:ZigBee:xxxxxxxxxxxx.TemperatureOffset.offset

Bei RoomClimateControl steht bei mir überall auch 0. Ich weiß nicht genau warum es diese Werte dort überhaupt gibt.

Viele Grüße
Chris

**Comment by simon2022** [comment]
Hallo @holomekc,
danke für die schnelle und kompetente Hilfe.
Du hast recht, daran lag es. Jetzt funktioniert es einwandfrei.

Vielen Dank!!
