### ISSUE TITLE
Zu ioBroker Liste hinzufügen

### ISSUE THREAD

**Issue by steckenpferd** [holomekc/ioBroker.bshb#3]
Wäre toll wenn der Adapter im latest Release auch auf der ioBroker Liste erscheinen könnte:
http://download.iobroker.net/list.html

**Comment by holomekc** [comment]
Hi. Der Pull request ist schon erstellt. Das dauert ein bisschen:
https://github.com/ioBroker/ioBroker.repositories/pull/526

**Comment by steckenpferd** [comment]
Geschafft :-) - kann dann jetzt geschlossen werden
