### ISSUE TITLE
Question: Activate "LOW"-mode on thermostats/in rooms

### ISSUE THREAD

**Issue by freakadings** [holomekc/ioBroker.bshb#30]
Hi, thank you for your work!

I've got a question: How do i set the thermostats to mode "LOW" (hat "low" is shown on the Display) or is this not possible?
The story behind my question is, that i want to use mostly aqara sensors, since they are way cheaper, smaller and in my eyes prettier than the bosch-ones

What i tried so far:
I compared two rooms on one the low mode is activated and in another its not. It seems that three values change:
"low" (but its role is "indicator.lowbat" which translates to me as the battery status is low?!
"setpointTemperature" is dropped to 8°C which seems logical.
"ventilationMode" is set to "true" seems logical too.

But when i set these values manualy, it seems that the "low"-mode is not activated, the display on the thermostats shows 8°C and within the bosch-app "low" is not shown either.

Greetings,
Merlin

**Comment by holomekc** [comment]
Hi. 
I guess in case of low you mean the mode the thermostat switches to when a door/window contact is connected and configured for ventilation detection?

**Answer:**
No this is not possible (See last section of this answer though). The link between thermostat and door/window contact is handled by the controller. The adapter is only able to use the provided interface of the controller, which does not allow such kind of configurations.

**Details:**
I did some tests and set RoomClimateControl.low to true (you can see messages send to controller if you set logging to silly) and although the controller says 204 (which basically means ok, but i have no answer for you) it does not provide an update to confirm that the value was changed. Also no changes on the device itself. But the RoomClimateControl.low state is definitely the correct value for that. I can see that it changes when I open/close my window where Bosch contact is setup. Then I checked the ventilation service. But it only lists the door/window contacts and allows to configure a delay.

**indicator.lowbat**
But you are correct the indicator.lowbat role is a mistake. The value for low battery can be seen here:
https://github.com/holomekc/ioBroker.bshb/wiki/Value-you-may-not-see-at-first
So e.g. hdm:HomeMaticIP:...BatteryLevel.faults and is only visible / part of the list when the fault occurs.

I will check if there is a suitable role in ioBroker for that and fix that issue. For the time beeing you can always overwrite roles.

**What you can do**
But what you can do is to define such a mode manually. One way would be to activate sommer mode in the room when window is open and disable summer mode when window is closed. Make sure to disable boost mode first though. It is not possible to set both values to true at the same time. The only difference I see is that you would see OFF on the device.

Br,
Christopher

**Comment by freakadings** [comment]
Wow, thanks a lot for this detailed answer!
Does the low-mode some bosch-internal magic or does it only change the temperature to 8°C (and changes the text on the display)? Thank you for your tip with the summer mode, i'll use this for now!

**Comment by holomekc** [comment]
Hi,
I am not 100% sure what low-mode does. I can only hear that the thermostat closes the valve. Maybe it just sets temperature to 8°C . Do be honest this is the only thing the thermostat can do ;) Open and close. So Yeah. You could do something like this as well. I guess summer mode is easier because it does not change anything regarding mode (manual, automatic) or temperature settings or even schedule.

Br,
Christopher

**Comment by holomekc** [comment]
Fixed in https://github.com/holomekc/ioBroker.bshb/pull/32/commits/5448dc202d9248f97a7f55c0b718cc46c3af456c

Role of existing objects will not change. So you can change it manually or you can delete the part and the adapter will recreate it.
