### ISSUE TITLE
Migrate to API 2.1

### ISSUE THREAD

**Issue by sebastianharder** [holomekc/ioBroker.bshb#37]
Support for API 1.0 is dropped, see BoschSmartHome/bosch-shc-api-docs#46

Migration to 2.1 is required.

**Comment by holomekc** [comment]
Thx for the information. I will take a look

**Comment by holomekc** [comment]
Update is done:
https://github.com/holomekc/ioBroker.bshb/commit/8b9a5ad84af591e038a35feae7c5b32cfccc64f6

I added a new folder called intrusionDetectionControl which allows:
* arm full protection
* arm partial protection
* arm individual protection
* disarm protection
* mute protection

Reading works as before. New version is prepared:
https://github.com/ioBroker/ioBroker.repositories/pull/1103
