### ISSUE TITLE
Log file of IO Broker logs following message: has to be stringified but received type "object".

### ISSUE THREAD

**Issue by Asche1985** [holomekc/ioBroker.bshb#47]
Hi everyone, 
the log file of my io broker logging following message:

State value to set for "bshb.0.hdm:HomeMaticIP:xxx.PowerMeter.faults" has to be stringified but received type "object".

Is that a bug or a configuration error. 

I use 
iobroker version: 3.3.11
Io Broker Admin: 5.1.6 
bshb: 0.1.13

Maybe you can help me

**Comment by holomekc** [comment]
Hi. Sorry for my late reponse. Does this still occur? The adapter itself intentionally use object as type there.  When you check:
https://github.com/holomekc/ioBroker.bshb/wiki/Value-you-may-not-see-at-first
You can see that a fault from api may look like this:

```json
"faults":{ 
      "entries":[ 
         { 
            "type":"LOW_BATTERY",
            "category":"WARNING"
         }
      ]
   }
```
The adapter then extracts the entries part and store it as an array to the faults value.

I tried to reproduce that but I cannot see a similar error in the logs. I am using version: 3.2.16 and Admin 5.1.10

Can you check the role of the mentioned value? It should be list. If not. You can try to remove the value and restart the adapter.
Do you have thermostats? If so do you see similar logs for ...RoomClimateControl.schedule?

**Comment by Thomas-Doc** [comment]
Den Fehler bekomme ich auch seit heute, hängt bei mir eindeutig mit meinen heutigen updates zusammen (auf 3.3.15, aber auch admin adapter und javascript geupdatet). Leider weiß ich nicht genau welches ...

seit heute:
iobroker: 3.3.15
admin: 5.1.23

... unverändert: bshb 0.1.13

<html><body>


bshb.0 | 2021-08-07 21:44:18.280 | info | State  value to set for  "bshb.0.hdm:HomeMaticIP:3014F711A000049BB859CB63.PowerMeter.faults" has  to be stringified but received type "object"
-- | -- | -- | --
bshb.0 | 2021-08-07 21:44:08.827 | info | State  value to set for  "bshb.0.hdm:HomeMaticIP:3014F711A000049BB859CB87.PowerMeter.faults" has  to be stringified but received type "object"
bshb.0 | 2021-08-07 21:42:56.926 | info | State  value to set for  "bshb.0.hdm:HomeMaticIP:3014F711A000049BB85A1E32.PowerMeter.faults" has  to be stringified but received type "object"
bshb.0 | 2021-08-07 21:41:01.285 | info | State  value to set for  "bshb.0.hdm:HomeMaticIP:3014F711A0000498785901A2.PowerMeter.faults" has  to be stringified but received type "object"
bshb.0 | 2021-08-07 21:40:12.694 | info | State value to set for "bshb.0.hdm:ZigBee:000d6f001043cf16.LatestMotion.faults" has to be stringified but received type "object"


</body>
</html>

Hab diese neu eingeführte Typprüfung auch wo gelesen, wurde auch diskutiert, find es aber im Moment gerade nicht.

Ganz schlimm ist es aber mit dem synology Adapter geworden, da kommt eine flut von "infos", den musste ich abschalten. BSHB ist für mich so wichtig, da nehm ich die infos halt in Kauf.

<html><body>


synology.1 | 2021-08-07 22:08:34.736 | info | State  value to set for  "synology.1.DiskStationManager.hdd_info.sata_drive_2.ebox_order" has to  be type "string" but received type "number"
-- | -- | -- | --
synology.1 | 2021-08-07 22:08:34.733 | info | State  value to set for  "synology.1.DiskStationManager.hdd_info.sata_drive_1.capacity" has to be  type "number" but received type "string"
synology.1 | 2021-08-07 22:08:34.731 | info | State  value to set for  "synology.1.DiskStationManager.hdd_info.sata_drive_1.ebox_order" has to  be type "string" but received type "number"
synology.1 | 2021-08-07 22:08:34.727 | info | State value to set for "synology.1.DiskStationManager.info.upgrade_ready" has to be type "string" but received type "boolean"
synology.1 | 2021-08-07 22:08:34.726 | info | State  value to set for "synology.1.DiskStationManager.info.is_system_crashed"  has to be type "string" but received type "boolean"
synology.1 | 2021-08-07 22:08:34.725 | info | State value to set for "synology.1.DiskStationManager.info.memory_size" has to be type "string" but received type "number"
synology.1 | 2021-08-07 22:08:34.722 | info | State value to set for "synology.1.DiskStationManager.info.uptime" has to be type "string" but received type "number"


</body>
</html>

Grüße Thomas

**Comment by Thomas-Doc** [comment]
Wahrscheinlich lässt sich der Fehler reproduzieren, wenn du auf 3.3.15 updatest. Dann gibt es diese zusätzlichen "infos"
Vermutlich hängt es damit zusammen:
Developer relevant DEPRECATIONS/WARNINGS

    (foxriver76) added new checks for setState:
        if strictObjectChecks are activated we now perform additional checks
        require common.type on state objects
        if state is read only and we get ack false -> not allowed
        check type of the state.val matching the common.type of the obj
        if it's a number and min/max is defined on object we perform additional checks for min and max
    (bluefox) checkPassword(Async) is now returning two parameters in callback/resolve (first is boolean if password/user are valid, second is the final internal username in form system.user.xxx)
    (bluefox) add _design/custom to the controller objects - this should deprecate the own custom view over time, please update if relevant!

**Comment by holomekc** [comment]
Hi. Ich vermute das kommt nur, wenn auch tatsächlich ein Fehler angezeigt wird. Ich muss mal schauen das ich bei mir ein Fehler forciere. Batterie rausnehmen müsste gehen. 
Mir ist noch nicht klar warum ich das Objekt als String umwandeln soll, aber vielleicht hängt es auch mit den type, role Informationen zusammen. Ich dachte ich hatte list angegeben für fault. Ich mein es ist dann ein Array von Objekten aber vielleicht darf ich das nicht mehr.

Ich habe gerade keinen Rechner zur Hand, aber wenn es in diese Richtung geht, dann wird es ein wenig problematischer. Das Problem das ich habe ist, dass ich nicht alle Werte kenne und es gibt auch Werte die nur unter bestimmten Bedingungen überhaupt erscheinen. Aber auch diese kenne ich nicht. Daher war es dynamisch gehalten damit der Adapter probiert die Werte anzuzeigen die er gerade erhält.

Aber eigentlich müsste er dann auch bei Raumtemperatur… schedule nörgeln. Da steht ja das ganze Profil drin. Hmm.

Ich schaue mal. Wenn ihr noch ähnliche Fehler findet bitte hier sammeln.

**Comment by Thomas-Doc** [comment]
Vielleicht hilft das hier weiter:
https://forum.iobroker.net/topic/45009/fehler-nach-update-js-controller-3-3-9/3?_=1628421451027&lang=de

Ab Version 3.3 des js-controllers sollen keine Objekte / Arrays mehr in Datenpunkte geschrieben werden, sondern nur noch per JSON.stringify(obj) gewandelte Objekte. **Diese Info-Logs sollen die Adapter-Entwickler informieren, dies anzupassen.**
Wenn die Logs stören, stelle die Log-Stufe des js-controllers in der Datei /opt/iobroker/iobroker-data/iobroker.json auf "warn" (anschließend ioBroker neu starten).


.... wenn ich das recht verstehe, müsstest du beim Schreiben aller Datenpunkte ein "JSON.stringify(obj)" setzen ...  Aber wenn du nicht alle Datenpunkte vorher kennst, dann übersteigt das meine Fähigkeiten und ich kann da nicht mehr mitreden.

**Comment by holomekc** [comment]
Hallo zusammen. Der Adapter ist jetzt in GitHub aktualisiert. Sorry das es so lange gedauert hat. Es wäre schön, wenn ihr auch die Version testen könntet, bevor ich diese dann veröffentliche. Aktuell läuft es bei mir und es sah ganz gut aus.

Ich musste mehr umstellen als gedacht und es sind ein paar Kleinigkeiten hinzugekommen

**Comment by Asche1985** [comment]
Hi, 
ich habe es mal ausprobiert und bisher sieht das alles gut aus. Ich habe die Hinweise nicht mehr. Würde sagen, dass mein Problem behoben ist. Danke für die Arbeit 👍

**Comment by Thomas-Doc** [comment]
Ja, sieht auch bei mir gut aus. Ich denke, das Problem ist gelöst, vielen Dank für die professionelle Arbeit!
Hab allerdings ein neues Problem, hierfür neuer issue eröffnet ...

**Comment by holomekc** [comment]
Danke für das Feedback. Damit schließe ich dieses Issue.
