### ISSUE TITLE
Rauchwarnmelder Alarm über ioBroker aktivieren

### ISSUE THREAD

**Issue by RicoSpohn** [holomekc/ioBroker.bshb#71]
Kann man über die ioBroker Objekte den Warntongeber des Rauchwarnmelders aktivieren? Dies wäre für eine externe Auslösung eines Alarmes sehr hilfreich (z.B. über Taster oder Gasmelder eines Drittanbieters).

**Comment by holomekc** [comment]
Hallo. Sorry für die späte Antwort. Ich habe zwar keinen Rauchmelder. Dafür aber den Twinguard von Bosch. Soweit ich das gesehen habe kannst du nicht direkt den Alarm auslösen. Es ist zwar möglich Auslöser zu konfigurieren, diese müssen jedoch auch am Bosch Controller angemeldet sein. 

Den einzigen Ansatz den ich kenne, andere Geräte in den Controller von Bosch zu bekommen ist die hue Erweiterung. Mit einer simulierten hue bridge, konnte ich Lichter hinzufügen und diese in Szenarien etc verwenden. Ich glaube zwar nicht das es geht, aber wenn müsste man einen Bewegungsmelder über hue simulieren und hoffen das dieser als Trigger auszuwählen ist. Laut der App von Bosch sieht das aber nicht so aus als wäre das unterstützt.

**Comment by holomekc** [comment]
Ich habe bisher nichts gegenteiliges gehört. Daher schließe ich diese Issue. Falls es noch fragen gibt einfach jeder Zeit hier.
