### ISSUE TITLE
Szenen als Auslöser für Skripte

### ISSUE THREAD

**Issue by NutzerXY** [holomekc/ioBroker.bshb#82]
Guten Abend allerseits,

ich suche nach einer Möglichkeit mithilfe meines Bosch-Twists Skripte in IoBroker zu triggern. 

Mittels IoBroker sehe ich die in der Bosch-App angelegten Szenen und sehe, dass diese auch über Zeitstempel verfügen. Meine Idee war es jetzt diese Zeitstempel als Trigger meiner Skripte zu verwenden. Leider musste ich feststellen, dass die Zeitstempel bei Ausführung der Szene  nicht durch Bosch verändert werden, bzw. diese Werte nicht übertragen werden.

Besteht eine Möglichkeit Skripte in IoBroker mittels des Twists auszuführen?

Lieben Dank im voraus 👍💯

**Comment by holomekc** [comment]
Hi,

jein :) aktuell wüsste ich nicht wie es mit den mitteln die der Adapter bietet gehen könnte. Außer das es sehr umständlich über hue sim gehen würde. Was ich aber gerade probiert habe ist ein Szenario über Twist auszuführen. Auch wenn im Adapter dann nicht viel zu sehen ist, kann ich sehen das der Adapter eine Nachricht erhält:
```json
["{\"result\":[{\"@type\":\"scenarioTriggered\",\"name\":\"Alarm an\",\"id\":\"0fd48cfb-f20a-483a-9a2c-633f1f3a8ba6\",\"lastTimeTriggered\":\"1636673694464\"}],\"jsonrpc\":\"2.0\"}\n"]
```

Zwei Dinge die ich tun kann:

1. Szenarien im Adapter erweitern, so dass nicht nur die Möglichkeit besteht diese zu auszuführen, sondern auch die letzte Ausführung anzeigt. Du meintest das der Zeitstempel nicht aktualisiert wird? Habe ich jetzt noch nicht geprüft.
2. Ein state hinzufügen, welcher alle status updates entgegen nimmt, so dass auch das json wie oben zu sehen so als Wert gesetzt wird und dann benutzt werden kann.

Bei Punkt 1 bin ich mir noch nicht sicher, ob ich kurzzeitig einmal den Button auf true setze mit neuem Zeitstempel oder nicht abwärtskompatibel die Struktur ändere. Muss ich ein wenig testen. Aber ich denke Punkt 2 macht so oder so Sinn. Das ist viel flexibler, selbst wenn Bosch etwas ändert/hinzufügt, kann darüber immer die Nachricht gelesen werden, so wie sie vom Controller kommt.

Am Wochenende schaffe ich das vielleicht. Mal schauen.

**Comment by NutzerXY** [comment]
Das klingt als würdest du das Problem lösen können 😍
Ich bin gespannt und hoffe, dass es nicht all zu viel Aufwand sein wird. 

Genau, führt Bosch ein Szenario aus, wird leider nicht der Zeitstempel verändert. 

Ich bin gespannt!! 

Danke dir schon mal!

**Comment by holomekc** [comment]
0.1.16 ist jetzt in GitHub verfügbar. Heißt installieren lässt es sich aktuell nur über manuelle Installation von eben GitHub. Update via ioBroker wenn ich ein bissle Zeit hatte noch mehr zu testen oder Feedback kommt, dass etwas nicht funktioniert.

Für die Szenarien im scenarios Ordner gilt nun:
Szenario aus iobroker ausgelöst:
1. state: true, ack: false
2. state: true, ack: true
3. 1s Verzögerung
4. state: false, ack: true

Szenario von woanders ausgelöst:
1. state: true, ack: true
2. 1s Verzögerung
3. state: false, ack: true

Davon abgesehen gibt es einen neuen Zustand "bshb.0.updates", welcher jede Nachricht erhält die vom Controller empfangen wurde. 

Ich hoffe das hilft weiter. Falls etwas nicht passt oder du eine andere Idee hast wäre ich für Feedback dankbar.

Viele Grüße
Christopher

**Comment by NutzerXY** [comment]
Guten Abeeeend,

1. und 2. (und deinen abschließenden Worte): Die Buttons mit Switches zu ersetzen, würde mein Leben um einiges vereinfachen!! Ob es jedoch irgendwelche Nachteile bergen könnte, weiß ich leider nicht. 
3. Um das umzusetzen (und meine Meinung dazu abzugeben) muss ich mich in den nächsten Tagen / Wochen mal mit deinem Code auseinandersetzen. Dass du den Zeitstempel aber nicht ändern möchtest, ist auf jedenfall nachvollziehbar! 

Liebe Grüße 🖖

**Comment by holomekc** [comment]
Ok. Also button -> switch habe ich noch eingepflegt und PR ist erstellt:
https://github.com/ioBroker/ioBroker.repositories/pull/1534

Kann ein bissle dauern bis es in ioBroker angezeigt wird.

@NutzerXY, einfach die Version 1.1.16 erneut drüber installieren, dann solltest du auch mit switch arbeiten können. Bei intrusion-detection musst du die Rolle leider manuell anpassen oder löschen und Adapter neustarten, da diese Werte nur einmal gesetzt werden. Bei scenario überschreibt er es immer noch. Ich muss hier mal schauen, ob ich das in Zukunft auch dort ändern kann.

Hiermit schließe ich das Issue. Falls es noch fragen gibt einfach erneut öffnen.
