### ISSUE TITLE
Yale Linus BSH ioBroker

### ISSUE THREAD

**Issue by alex030** [holomekc/ioBroker.bshb#83]
Hi zusammen,

seit kurzem ist es nun möglich die Yale Linus Schlösser ins BSH einzubinden. Hat das schon jemand gemacht und kann zu Erfahrungen in Bezug auf die ioBroker-Integration berichten? Ist das Schloss dann wie alle anderen BSH Geräte über die API direkt in ioBroker als Datenquelle verfügbar?

Vielen Dank für eure Erfahrungen

**Comment by holomekc** [comment]
Hi,
ich kann leider nichts genaues dazu sagen. Der Adapter ist so geschrieben, dass er über die allgemeinen Schnittstellen (device, deviceservices) alles anbietet was gefunden wird. Falls Bosch nicht eine neue Schnittstelle für diese Geräte hinzugefügt hat, dann sollte es auch so funktionieren. In der API von Bosch konnte ich auch hier nichts zu finden:
https://apidocs.bosch-smarthome.com/local/ 

Ich gehe davon aus das es funktioniert, aber garantieren kann ich es leider nicht. Zumindest bei der Hue Integration funktioniert es. Was auf jeden Fall fehlen wird, sind die vordefinierten Rollen für die Werte vom Schloss, dazu fehlen mir die Bezeichnungen des Yale Linus Schlosses. Diese Art der Werte pflege ich hier: https://github.com/holomekc/ioBroker.bshb/blob/master/src/definition/roles.ts

Ich kann es aber gerne nachpflegen, wenn mir jemand die Daten gibt.

**Comment by alex030** [comment]
Hi,

vielen Dank für deine Antwort. Ich habe es einfach mal versucht. Yale Schloss organisiert und eingebunden. Es wird, wie von dir vermutet, einfach durchgereicht. Lock & Unlock funktioniert aus ioBroker. Es gibt, so weit ich es bislang anschauen konnte, 4 Zustände: "LOCKED", "UNLOCKED", "LOCKING", "UNLOCKING". Reicht dir das?

So weit so gut. Was mir allerdings auf den ersten Blick aufgefallen ist, ist dass es beim Schloss sobald es auf Status "UNLOCKED" gesetzt wird, zwar wunderbar aufschließt, allerdings auch die Schloss-Falle öffnet. Somit geht die Tür auf. Das ist nicht wie benötigt umgesetzt. Aus der Yale App verhält es sich identisch. Daher kein ioBroker/BSH Thema, sondern eins von Yale bezüglich des Zustandes. Benötigt wird "LOCKED", "UNLOCKED" und zusätzlich "etwas wie OPEN". Im ioBroker ist mir ein Attribut ins Auge gestochen. Es wird "canUnlatch" genannt. Das steht bei mir auf "true". Wenn ich es auf "false" ändere, wird es direkt wieder überschrieben. Das könnte der Ansatz sein. Weiß hierzu jemand bereits mehr?

![Bildschirmfoto 2021-11-23 um 11 01 12](https://user-images.githubusercontent.com/1160611/143005013-bd504f81-8edd-4afd-b70e-8c14cb6f9612.png)
r?

**Comment by holomekc** [comment]
Sorry für die späte Antwort. Ich schaue das ich die Werte mit aufnehme und in der nächsten Version integriere.

**Comment by holomekc** [comment]
Hi doch noch einmal kleine Rückfragen:

DoorSensor.doorState: DOOR_UNKNOWN, DOOR_OPEN, DOOR_CLOSED?

Das ist das was du am suchen warst oder? Ich glaube nicht das es beim lockState sein wird. Vielleicht ist dieser Wert bei dem Schloss nicht bekannt?

canUnlatch ist glaube ich nicht editierbar. Klingt vom Namen her eher nach einem unveränderlichen Attribut des Schloss.

**Comment by holomekc** [comment]
0.1.17 ist in GitHub verfügbar. Habe für doorState die Werte oben genommen. Passt zumindest zu dem was ich sonst bei Bosch so gesehen habe. 

Update via ioBroker. Dauert ein bissle ich lasse das immer ein wenig bei mir laufen und schaue, ob ich neben den normalen Tests noch was auffälliges sehe.
