### ISSUE TITLE
BshbError: timeout during call to BSHC - system down // BSHcontroller overflow 

### ISSUE THREAD

**Issue by kesch001de** [holomekc/ioBroker.bshb#91]
**Describe the bug**  
Starting the adapter, the protokoll will show hundreds of messages "BshbError: timeout during call to BSHC".
Messages are in milliseconds.

The connection green, adapter can be started.
But, the controller is down and cannot handle any requests anymore.

**To Reproduce**  
Just start the adapter and the issue will start.

**Expected behavior**  
It was not like that before. It happend 2 days ago the first time.
After last controller update all was still fine.
It started i guess 1 or 2 days after the controller update.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

bshb.0 | 2021-12-24 10:19:48.305 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.301 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.298 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.295 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.292 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.289 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.285 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.282 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.279 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.276 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.273 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.269 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.267 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.263 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.261 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.256 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.253 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.250 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.247 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.242 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.239 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.236 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.232 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.227 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.224 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.221 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.218 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.215 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.211 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.208 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.205 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.200 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.197 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.194 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.190 | error | BshbError: timeout during call to BSHC
bshb.0 | 2021-12-24 10:19:48.189 | error | BshbError: timeout during call to BSHC

**Versions:**
- Adapter version: v0.1.16
- JS-Controller version: 3.3.21
- Node version: v12.22.7
- Operating system: raspberrypi
Plattform linux
Betriebssystem linux
Architektur arm
CPUs 4
Geschwindigkeit 1500 MHz
Modell ARMv7 Processor rev 3 (v7l)
RAM 7.71 GB

Linux version 5.10.60-v7l+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1449 SMP Wed Aug 25 15:00:44 BST 2021

**Additional context**

**Comment by holomekc** [comment]
Hi. Please start the adapter with silly logging. Then you can see every request of the adapter against the controller and way more information about the issue. I guess there is still something I could do to improve the logging of the adapter.

**Comment by kesch001de** [comment]
hi @holomekc, many thx for your reply.
the adapter creates abt 40mb of logs when it starts. anything in particular i should share here?
Or should / can i just post the whole log here? There are a lot of system details in there - its that okay to post here?
thx and merry xmas :) 

Some more details are in the attached log. Just some lines out of the whole log file.
[20211225_iob_BSH_log.txt](https://github.com/holomekc/ioBroker.bshb/files/7775732/20211225_iob_BSH_log.txt)

**Comment by holomekc** [comment]
Hi can you disable your script for testing purposes it looks like that the script is setting values on/off all the time which leads to too man requests for the adapter:

BoschSmartHome.AZ_Schreibtisch

When disabled start the adapter again and check if it is back to normal.

**Comment by kesch001de** [comment]
hi @holomekc, 
awesome, thats it.

very strange behaviour actually.  disabling the script helped and the adapter started without any issues.
after the bsh adapter was up and running, i could start the script again without any further issues.
leaving the script active and starting the adapter now, all fine. no further issues.

actually, the script does not do that much - just checking the status and writing it in another object (see attached). 
![20211225_AZ Schreibtisch_Script](https://user-images.githubusercontent.com/68777942/147389151-25e9f477-6e00-4f10-8945-6ac04af4d7e5.PNG)

But anyways, i will keep an eye on it. 
Maybe its not at all related to the bsh adpater. maybe more likely a script issue.

many thanks for your fast xmas support! much appreciated!

**Comment by holomekc** [comment]
Hi. Ich wechsle mal auf Deutsch 😀. Ich denke es wird der erste Block. Dort steht Auslösung durch "egal" vom gleichem Wert der auch gesetzt wird. Klingt für mich wie eine Endlosschleife. Aber ich habe noch nie so richtig mit Blockly gearbeitet. Aber komisch das dies nicht immer passiert. Eigentlich müsste es vorkommen, sobald sich der Wert ändert.

Frohe Weihnachten und Danke für die lieben Worte.
